export const surpriseMePrompts = [
  "a floating city above the clouds, illuminated by neon lights, cyberpunk style",
  "an octopus bartender in a deep-sea speakeasy, serving glowing drinks, digital art",
  "a cosmic dragon made of galaxies and stars soaring through space, ultra-detailed",
  "a futuristic samurai with a laser katana standing on a skyscraper at sunset, cyberpunk",
  "a giant clockwork owl with gears and glowing eyes, steampunk illustration",
  "a portal to another universe hidden inside an old library, cinematic fantasy",
  "a wizard cat casting spells in a magical floating tower, dreamy fantasy art",
  "a vintage train traveling through a surreal desert with floating islands, hyper-realistic",
  "a mystical jellyfish floating above a neon-lit cyber city, sci-fi artwork",
  "a pirate ship sailing through the stars instead of the sea, with glowing nebula clouds",
  "an ancient temple hidden in a futuristic jungle, overgrown with bioluminescent plants",
  "a werewolf detective in a noir 1920s city, black and white photography style",
  "a robot monk meditating under a waterfall, blending nature and technology",
  "a phoenix rising from an ocean of molten gold, dramatic fantasy painting",
  "a time traveler stepping out of a glowing portal, with multiple timelines overlapping",
  "a fairy-tale castle built entirely from candy, with chocolate rivers and gumdrop trees",
  "a steampunk airship docked at a floating island, intricate details, breathtaking view",
  "a gothic vampire queen sitting on a throne of ice, eerie yet elegant atmosphere",
  "a glowing crystal cave with an ancient dragon curled around its treasure",
  "a cybernetic tiger prowling through a futuristic jungle, neon aesthetics",
  "a cosmic knight in shining armor, wielding a sword made of pure stardust",
  "a parallel universe where humans have butterfly wings, hyper-realistic fantasy",
  "a dystopian city where robots and humans coexist, with flying cars and neon billboards",
  "a mermaid warrior riding a giant seahorse, deep in an ancient underwater kingdom",
  "a golem made of molten lava, standing guard over an ancient ruin",
  "a samurai duel at sunset, with glowing cherry blossom petals swirling around",
  "a haunted Victorian mansion where the paintings move and whisper secrets",
  "a mystical fox with nine glowing tails, surrounded by floating lanterns",
  "a futuristic cyber-cowboy riding a mechanical horse, wild west meets sci-fi",
  "a shattered moon hovering above an alien planet, with floating rock formations",
  "a robot painter creating a masterpiece, blending technology and fine art",
  "a grand library inside a floating space station, endless bookshelves stretching into the stars",
  "a steam-powered mech fighting a colossal sea monster, epic battle scene",
  "a lighthouse guiding a spaceship through an intergalactic storm",
  "a magical doorway in the middle of a dense forest, leading to another dimension",
  "a rock concert in an alien world, with extraterrestrial musicians and neon light effects",
  "a gargoyle waking up at dusk, stretching its stone wings above a gothic city",
  "a mystical deer made of constellations, standing in an enchanted moonlit forest",
  "a fairy village built inside a giant mushroom, glowing softly at twilight",
  "a cyberpunk angel with mechanical wings, soaring through a neon-lit skyline",
  "a storm god summoning lightning, standing atop a dark mountain",
  "a giant whale swimming through the sky, surrounded by floating islands",
  "a hidden utopia deep inside a massive cave, glowing with bioluminescent plants",
  "a surreal dreamscape with floating staircases and impossible architecture",
  "a futuristic gladiator arena, where augmented warriors battle with holographic weapons",
  "a clock tower frozen in time, standing alone in a vast, mysterious landscape",
  "a haunted spaceship drifting through deep space, eerie horror sci-fi vibe",
  "a biomechanical forest where trees have glowing circuits instead of bark",
  "an astronaut surfing a solar flare, illuminated by the sun’s plasma waves",
  "a neon-lit underwater metropolis, home to an advanced civilization of deep-sea creatures",
  "a colossal ancient god awakening beneath the Arctic ice, surrounded by explorers",
  "a celestial ballroom where planets and stars dance in harmony, cosmic elegance",
  "a Viking warrior standing atop an asteroid, wielding a glowing energy axe",
  "a candy-colored cyberpunk city where all vehicles hover and neon signs pulse rhythmically",
  "a gothic castle floating in the sky, shrouded in mist and lightning",
  "a futuristic Zen garden where robotic koi fish swim in pools of liquid metal",
  "a spaceship shaped like an enormous whale, traveling between galaxies",
  "a digital waterfall cascading through a virtual landscape, blending nature and technology",
  "a secret cyberpunk nightclub hidden behind a holographic alleyway",
  "an ice dragon resting in a cavern of frozen sapphire crystals, glowing with blue light",
  "a cosmic chessboard where celestial beings play with planets and black holes",
  "a mystical wolf with glowing tribal markings, standing beneath the aurora borealis",
  "a post-apocalyptic city reclaimed by nature, with overgrown skyscrapers and wildlife roaming",
  "a futuristic palace made of mirrors and prisms, reflecting endless rainbows",
  "a colossal library inside a hollowed-out asteroid, holding the knowledge of the universe",
  "a robot king ruling over a court of android nobles in a neon-lit castle",
  "a steampunk airship docking station floating above a crimson ocean at sunset",
  "a dragon made of ice and fire, its wings glowing with an ever-changing hue",
  "a legendary blacksmith forging weapons for interdimensional warriors, sparks flying in a cosmic forge",
];
